-- ardour_actions.lua
--
--  ====    ====    ====  
-- ==  ==  ==  ==  ==  == 
-- ==      ==      ==  == 
-- ==       ====   ==  == 
-- ==          ==  ==  == 
-- ==  ==  ==  ==  ==  == 
--  ====    ====    ====  
-- Control Surface Object 

-- library script for CSO:
-- populate global table 'aa' with ardour actions.
-- in a nutshell:
-- aa.component:action()
-- aa.Editor:select_next_route()

-- original ardour action names that contain a '-' will be accessible through using '_':

-- existing OSC call                              lua binding (no OSC involved)
-- /access_action s 'Editor/select-next-route' -> aa.Editor:select_next_route()

-- actions don't take an argument.

-- convenience functions on components:
-- :list()
-- :find(pattern)
-- :dump() --for debug
-- aa.Editor.find('^next_') -- prints all actions in component Editor that start with 'next_'

aa={}

-- to update table ardour_action_tokens (this should not happen too frequently):

-- get list of bindable actions from ardour:
-- ardour5 --bindings > ardour_actions.txt

-- ///OLD
-- preprocess:
-- cat ardour_actions.txt | cut -d'>' -f2- | cut -d" " -f1 | grep "^/" > ardour_actions_plain.txt
-- create lua code:
-- echo "ardour_action_tokens={" && cat ardour_actions_plain.txt | while read line; do echo "'"$line"',"; done && echo "}"
-- ///

-- starting from ardour git rev 5d5642d6ec22213b0b944936328a0ae005bf577c:
-- the bindings dump format changed and contains now a short description for every action.
-- preprocess:
-- (anytime the dump format changes this will break. this is odd.)
-- #cut away junk before partial HTML, make well-formed, enclose in root tag, escape ampersand, escape apos:
-- (echo "<actions>"; cat ardour_actions.txt | grep -A 100000 '^<h2>' | sed 's/ class="dl"//g' | sed 's/&/&amp;/g' | sed "s/'/\&apos;/g"; echo "</actions>") | xmlstarlet fo > ardour_actions.xml
-- #create lua array:
-- cat ardour_actions.xml | xmlstarlet sel -t -o 'local ardour_action_tokens={' -n -m "//tbody/tr" -o "'" -v th/kbd -o "'," -n -b -o '}' -n -n > ardour_actions.part
-- #cat ardour_actions.xml | xmlstarlet sel -t -o 'local ardour_action_tokens_description={' -n -m "//tbody/tr" -o "'" -v td -o "'," -n -b -o '}' -n -n >> ardour_actions.part
-- #replace ardour_action_tokens in this file
-- #handle with care
-- #cat ardour_actions.part >> ardour_actions.lua
-- #then move the appended array BEFORE functions, right here

-- ============================================================================
local ardour_action_tokens={
'/ProcessorMenu/ab_plugins',
'/ProcessorMenu/activate_all',
'/ProcessorMenu/backspace',
'/ProcessorMenu/clear',
'/ProcessorMenu/clear_post',
'/ProcessorMenu/clear_pre',
'/ProcessorMenu/controls',
'/ProcessorMenu/copy',
'/ProcessorMenu/cut',
'/ProcessorMenu/deactivate_all',
'/ProcessorMenu/delete',
'/ProcessorMenu/deselectall',
'/ProcessorMenu/edit',
'/ProcessorMenu/edit-generic',
'/ProcessorMenu/manage-pins',
'/ProcessorMenu/newaux',
'/ProcessorMenu/newinsert',
'/ProcessorMenu/newplugin',
'/ProcessorMenu/newsend',
'/ProcessorMenu/paste',
'/ProcessorMenu/rename',
'/ProcessorMenu/selectall',
'/ProcessorMenu/send_options',
'/Common/Hide',
'/Common/NewMIDITracer',
'/Common/Quit',
'/Common/Save',
'/Common/ToggleMaximalEditor',
'/Common/ToggleMaximalMixer',
'/Common/ToggleMixerList',
'/Common/ToggleMonitorSection',
'/Common/ToggleRecordEnableTrack1',
'/Common/ToggleRecordEnableTrack10',
'/Common/ToggleRecordEnableTrack11',
'/Common/ToggleRecordEnableTrack12',
'/Common/ToggleRecordEnableTrack13',
'/Common/ToggleRecordEnableTrack14',
'/Common/ToggleRecordEnableTrack15',
'/Common/ToggleRecordEnableTrack16',
'/Common/ToggleRecordEnableTrack17',
'/Common/ToggleRecordEnableTrack18',
'/Common/ToggleRecordEnableTrack19',
'/Common/ToggleRecordEnableTrack2',
'/Common/ToggleRecordEnableTrack20',
'/Common/ToggleRecordEnableTrack21',
'/Common/ToggleRecordEnableTrack22',
'/Common/ToggleRecordEnableTrack23',
'/Common/ToggleRecordEnableTrack24',
'/Common/ToggleRecordEnableTrack25',
'/Common/ToggleRecordEnableTrack26',
'/Common/ToggleRecordEnableTrack27',
'/Common/ToggleRecordEnableTrack28',
'/Common/ToggleRecordEnableTrack29',
'/Common/ToggleRecordEnableTrack3',
'/Common/ToggleRecordEnableTrack30',
'/Common/ToggleRecordEnableTrack31',
'/Common/ToggleRecordEnableTrack32',
'/Common/ToggleRecordEnableTrack4',
'/Common/ToggleRecordEnableTrack5',
'/Common/ToggleRecordEnableTrack6',
'/Common/ToggleRecordEnableTrack7',
'/Common/ToggleRecordEnableTrack8',
'/Common/ToggleRecordEnableTrack9',
'/Common/add-location-from-playhead',
'/Common/addExistingAudioFiles',
'/Common/alt-finish-range',
'/Common/alt-start-range',
'/Common/alternate-add-location-from-playhead',
'/Common/alternate-jump-backward-to-mark',
'/Common/alternate-jump-forward-to-mark',
'/Common/alternate-remove-location-from-playhead',
'/Common/attach-editor',
'/Common/attach-mixer',
'/Common/attach-preferences',
'/Common/change-editor-visibility',
'/Common/change-mixer-visibility',
'/Common/change-preferences-visibility',
'/Common/chat',
'/Common/cheat-sheet',
'/Common/detach-editor',
'/Common/detach-mixer',
'/Common/detach-preferences',
'/Common/finish-loop-range',
'/Common/finish-punch-range',
'/Common/finish-range',
'/Common/finish-range-from-playhead',
'/Common/forums',
'/Common/hide-editor',
'/Common/hide-mixer',
'/Common/hide-preferences',
'/Common/howto-report',
'/Common/jump-backward-to-mark',
'/Common/jump-forward-to-mark',
'/Common/key-change-editor-visibility',
'/Common/key-change-mixer-visibility',
'/Common/key-change-preferences-visibility',
'/Common/manual',
'/Common/menu-show-preferences',
'/Common/next-tab',
'/Common/nudge-next-backward',
'/Common/nudge-next-forward',
'/Common/nudge-playhead-backward',
'/Common/nudge-playhead-forward',
'/Common/playhead-backward-to-grid',
'/Common/playhead-forward-to-grid',
'/Common/previous-tab',
'/Common/reference',
'/Common/remove-location-from-playhead',
'/Common/set-session-end-from-playhead',
'/Common/set-session-start-from-playhead',
'/Common/show-preferences',
'/Common/start-loop-range',
'/Common/start-punch-range',
'/Common/start-range',
'/Common/start-range-from-playhead',
'/Common/toggle-location-at-playhead',
'/Common/toggle-luawindow',
'/Common/toggle-meterbridge',
'/Common/tracker',
'/Common/website',
'/Common/website-dev',
'/MIDI/panic',
'/Main/AddTrackBus',
'/Main/Archive',
'/Main/CleanupPeakFiles',
'/Main/CleanupUnused',
'/Main/Close',
'/Main/CloseVideo',
'/Main/EditMetadata',
'/Main/Escape',
'/Main/Export',
'/Main/ExportAudio',
'/Main/ExportVideo',
'/Main/FlushWastebasket',
'/Main/ImportMetadata',
'/Main/Metadata',
'/Main/New',
'/Main/Open',
'/Main/OpenVideo',
'/Main/QuickSnapshotStay',
'/Main/QuickSnapshotSwitch',
'/Main/Recent',
'/Main/Rename',
'/Main/SaveAs',
'/Main/SaveTemplate',
'/Main/Scripting',
'/Main/SnapshotStay',
'/Main/SnapshotSwitch',
'/Main/StemExport',
'/Main/cancel-solo',
'/Main/close-current-dialog',
'/Main/duplicate-routes',
'/Main_menu/AudioFileFormat',
'/Main_menu/AudioFileFormatData',
'/Main_menu/AudioFileFormatHeader',
'/Main_menu/Cleanup',
'/Main_menu/ControlSurfaces',
'/Main_menu/Denormals',
'/Main_menu/DetachMenu',
'/Main_menu/EditorMenu',
'/Main_menu/Help',
'/Main_menu/KeyMouseActions',
'/Main_menu/Metering',
'/Main_menu/MeteringFallOffRate',
'/Main_menu/MeteringHoldTime',
'/Main_menu/MixerMenu',
'/Main_menu/Plugins',
'/Main_menu/PrefsMenu',
'/Main_menu/Session',
'/Main_menu/Sync',
'/Main_menu/TransportOptions',
'/Main_menu/WindowMenu',
'/Options/SendMMC',
'/Options/SendMTC',
'/Options/SendMidiClock',
'/Options/UseMMC',
'/Transport/Forward',
'/Transport/ForwardFast',
'/Transport/ForwardSlow',
'/Transport/GotoEnd',
'/Transport/GotoStart',
'/Transport/GotoWallClock',
'/Transport/GotoZero',
'/Transport/Loop',
'/Transport/PlayPreroll',
'/Transport/PlaySelection',
'/Transport/Record',
'/Transport/RecordCountIn',
'/Transport/RecordPreroll',
'/Transport/Rewind',
'/Transport/RewindFast',
'/Transport/RewindSlow',
'/Transport/Roll',
'/Transport/SessionMonitorDisk',
'/Transport/SessionMonitorIn',
'/Transport/Stop',
'/Transport/ToggleAutoInput',
'/Transport/ToggleAutoPlay',
'/Transport/ToggleAutoReturn',
'/Transport/ToggleClick',
'/Transport/ToggleExternalSync',
'/Transport/ToggleFollowEdits',
'/Transport/TogglePunch',
'/Transport/TogglePunchIn',
'/Transport/TogglePunchOut',
'/Transport/ToggleRoll',
'/Transport/ToggleRollForgetCapture',
'/Transport/ToggleRollMaybe',
'/Transport/ToggleTimeMaster',
'/Transport/ToggleVideoSync',
'/Transport/TransitionToReverse',
'/Transport/TransitionToRoll',
'/Transport/Transport',
'/Transport/alternate-GotoStart',
'/Transport/alternate-ToggleRoll',
'/Transport/alternate-numpad-decimal',
'/Transport/alternate-record-roll',
'/Transport/focus-on-clock',
'/Transport/numpad-0',
'/Transport/numpad-1',
'/Transport/numpad-2',
'/Transport/numpad-3',
'/Transport/numpad-4',
'/Transport/numpad-5',
'/Transport/numpad-6',
'/Transport/numpad-7',
'/Transport/numpad-8',
'/Transport/numpad-9',
'/Transport/numpad-decimal',
'/Transport/primary-clock-bbt',
'/Transport/primary-clock-minsec',
'/Transport/primary-clock-samples',
'/Transport/primary-clock-timecode',
'/Transport/record-roll',
'/Transport/secondary-clock-bbt',
'/Transport/secondary-clock-minsec',
'/Transport/secondary-clock-samples',
'/Transport/secondary-clock-timecode',
'/Window/show-mixer',
'/Window/toggle-about',
'/Window/toggle-add-routes',
'/Window/toggle-add-video',
'/Window/toggle-audio-connection-manager',
'/Window/toggle-audio-midi-setup',
'/Window/toggle-big-clock',
'/Window/toggle-bundle-manager',
'/Window/toggle-idle-o-meter',
'/Window/toggle-inspector',
'/Window/toggle-key-editor',
'/Window/toggle-locations',
'/Window/toggle-midi-connection-manager',
'/Window/toggle-script-manager',
'/Window/toggle-session-options-editor',
'/Window/toggle-speaker-config',
'/Window/toggle-video-export',
'/Editor/SnapMode',
'/Editor/SnapTo',
'/Editor/ToggleGroupTabs',
'/Editor/ToggleJadeo',
'/Editor/ToggleMeasureVisibility',
'/Editor/ToggleSummary',
'/Editor/addExistingPTFiles',
'/Editor/addExternalAudioToRegionList',
'/Editor/alternate-alternate-redo',
'/Editor/alternate-editor-delete',
'/Editor/alternate-redo',
'/Editor/alternate-select-all-after-edit-cursor',
'/Editor/alternate-select-all-before-edit-cursor',
'/Editor/alternate-tab-to-transient-backwards',
'/Editor/alternate-tab-to-transient-forwards',
'/Editor/bring-into-session',
'/Editor/center-edit-cursor',
'/Editor/center-playhead',
'/Editor/crop',
'/Editor/cycle-edit-mode',
'/Editor/cycle-edit-point',
'/Editor/cycle-edit-point-with-marker',
'/Editor/cycle-snap-mode',
'/Editor/cycle-zoom-focus',
'/Editor/deselect-all',
'/Editor/duplicate',
'/Editor/edit-at-mouse',
'/Editor/edit-at-playhead',
'/Editor/edit-at-selected-marker',
'/Editor/edit-current-meter',
'/Editor/edit-current-tempo',
'/Editor/edit-cursor-to-next-region-end',
'/Editor/edit-cursor-to-next-region-start',
'/Editor/edit-cursor-to-next-region-sync',
'/Editor/edit-cursor-to-previous-region-end',
'/Editor/edit-cursor-to-previous-region-start',
'/Editor/edit-cursor-to-previous-region-sync',
'/Editor/edit-cursor-to-range-end',
'/Editor/edit-cursor-to-range-start',
'/Editor/edit-to-playhead',
'/Editor/editor-copy',
'/Editor/editor-crop',
'/Editor/editor-cut',
'/Editor/editor-delete',
'/Editor/editor-fade-range',
'/Editor/editor-paste',
'/Editor/editor-separate',
'/Editor/expand-tracks',
'/Editor/export-audio',
'/Editor/export-range',
'/Editor/fit-selection',
'/Editor/fit_16_tracks',
'/Editor/fit_1_track',
'/Editor/fit_2_tracks',
'/Editor/fit_32_tracks',
'/Editor/fit_4_tracks',
'/Editor/fit_8_tracks',
'/Editor/fit_all_tracks',
'/Editor/goto-mark-1',
'/Editor/goto-mark-2',
'/Editor/goto-mark-3',
'/Editor/goto-mark-4',
'/Editor/goto-mark-5',
'/Editor/goto-mark-6',
'/Editor/goto-mark-7',
'/Editor/goto-mark-8',
'/Editor/goto-mark-9',
'/Editor/goto-visual-state-1',
'/Editor/goto-visual-state-10',
'/Editor/goto-visual-state-11',
'/Editor/goto-visual-state-12',
'/Editor/goto-visual-state-2',
'/Editor/goto-visual-state-3',
'/Editor/goto-visual-state-4',
'/Editor/goto-visual-state-5',
'/Editor/goto-visual-state-6',
'/Editor/goto-visual-state-7',
'/Editor/goto-visual-state-8',
'/Editor/goto-visual-state-9',
'/Editor/importFromSession',
'/Editor/insert-time',
'/Editor/invert-selection',
'/Editor/lock',
'/Editor/main-menu-play-selected-regions',
'/Editor/move-range-end-to-next-region-boundary',
'/Editor/move-range-end-to-previous-region-boundary',
'/Editor/move-range-start-to-next-region-boundary',
'/Editor/move-range-start-to-previous-region-boundary',
'/Editor/move-selected-tracks-down',
'/Editor/move-selected-tracks-up',
'/Editor/multi-duplicate',
'/Editor/next-snap-choice',
'/Editor/next-snap-choice-music-only',
'/Editor/play-edit-range',
'/Editor/play-from-edit-point',
'/Editor/play-from-edit-point-and-return',
'/Editor/playhead-to-edit',
'/Editor/playhead-to-next-region-boundary',
'/Editor/playhead-to-next-region-boundary-noselection',
'/Editor/playhead-to-next-region-end',
'/Editor/playhead-to-next-region-start',
'/Editor/playhead-to-next-region-sync',
'/Editor/playhead-to-previous-region-boundary',
'/Editor/playhead-to-previous-region-boundary-noselection',
'/Editor/playhead-to-previous-region-end',
'/Editor/playhead-to-previous-region-start',
'/Editor/playhead-to-previous-region-sync',
'/Editor/playhead-to-range-end',
'/Editor/playhead-to-range-start',
'/Editor/prev-snap-choice',
'/Editor/prev-snap-choice-music-only',
'/Editor/quantize',
'/Editor/redo',
'/Editor/redo-last-selection-op',
'/Editor/remove-last-capture',
'/Editor/remove-time',
'/Editor/remove-track',
'/Editor/save-visual-state-1',
'/Editor/save-visual-state-10',
'/Editor/save-visual-state-11',
'/Editor/save-visual-state-12',
'/Editor/save-visual-state-2',
'/Editor/save-visual-state-3',
'/Editor/save-visual-state-4',
'/Editor/save-visual-state-5',
'/Editor/save-visual-state-6',
'/Editor/save-visual-state-7',
'/Editor/save-visual-state-8',
'/Editor/save-visual-state-9',
'/Editor/script-action-1',
'/Editor/script-action-2',
'/Editor/script-action-3',
'/Editor/script-action-4',
'/Editor/script-action-5',
'/Editor/script-action-6',
'/Editor/script-action-7',
'/Editor/script-action-8',
'/Editor/script-action-9',
'/Editor/scroll-backward',
'/Editor/scroll-forward',
'/Editor/scroll-playhead-backward',
'/Editor/scroll-playhead-forward',
'/Editor/scroll-tracks-down',
'/Editor/scroll-tracks-up',
'/Editor/select-all-after-edit-cursor',
'/Editor/select-all-before-edit-cursor',
'/Editor/select-all-between-cursors',
'/Editor/select-all-in-loop-range',
'/Editor/select-all-in-punch-range',
'/Editor/select-all-objects',
'/Editor/select-all-tracks',
'/Editor/select-all-within-cursors',
'/Editor/select-from-regions',
'/Editor/select-loop-range',
'/Editor/select-next-route',
'/Editor/select-prev-route',
'/Editor/select-punch-range',
'/Editor/select-range-between-cursors',
'/Editor/selected-marker-to-next-region-boundary',
'/Editor/selected-marker-to-next-region-boundary-noselection',
'/Editor/selected-marker-to-previous-region-boundary',
'/Editor/selected-marker-to-previous-region-boundary-noselection',
'/Editor/separate-from-loop',
'/Editor/separate-from-punch',
'/Editor/set-auto-punch-range',
'/Editor/set-edit-lock',
'/Editor/set-edit-point',
'/Editor/set-edit-ripple',
'/Editor/set-edit-slide',
'/Editor/set-loop-from-edit-range',
'/Editor/set-playhead',
'/Editor/set-punch-from-edit-range',
'/Editor/set-session-from-edit-range',
'/Editor/set-tempo-from-edit-range',
'/Editor/show-editor-list',
'/Editor/show-editor-mixer',
'/Editor/show-marker-lines',
'/Editor/shrink-tracks',
'/Editor/snap-magnetic',
'/Editor/snap-normal',
'/Editor/snap-off',
'/Editor/sound-midi-notes',
'/Editor/split-region',
'/Editor/step-mouse-mode',
'/Editor/step-tracks-down',
'/Editor/step-tracks-up',
'/Editor/tab-to-transient-backwards',
'/Editor/tab-to-transient-forwards',
'/Editor/temporal-zoom-in',
'/Editor/temporal-zoom-out',
'/Editor/toggle-follow-playhead',
'/Editor/toggle-log-window',
'/Editor/toggle-midi-input-active',
'/Editor/toggle-skip-playback',
'/Editor/toggle-stationary-playhead',
'/Editor/toggle-track-active',
'/Editor/toggle-vmon-frame',
'/Editor/toggle-vmon-fullscreen',
'/Editor/toggle-vmon-letterbox',
'/Editor/toggle-vmon-ontop',
'/Editor/toggle-vmon-osdbg',
'/Editor/toggle-vmon-timecode',
'/Editor/toggle-zoom',
'/Editor/track-height-large',
'/Editor/track-height-larger',
'/Editor/track-height-largest',
'/Editor/track-height-normal',
'/Editor/track-height-small',
'/Editor/track-mute-toggle',
'/Editor/track-record-enable-toggle',
'/Editor/track-solo-isolate-toggle',
'/Editor/track-solo-toggle',
'/Editor/undo',
'/Editor/undo-last-selection-op',
'/Editor/zoom-to-selection',
'/Editor/zoom-to-selection-horiz',
'/Editor/zoom-to-session',
'/Editor/zoom-vmon-100',
'/Editor/zoom_100_ms',
'/Editor/zoom_10_min',
'/Editor/zoom_10_ms',
'/Editor/zoom_10_sec',
'/Editor/zoom_1_min',
'/Editor/zoom_1_sec',
'/Editor/zoom_5_min',
'/EditorMenu/AlignMenu',
'/EditorMenu/Autoconnect',
'/EditorMenu/Crossfades',
'/EditorMenu/Edit',
'/EditorMenu/EditCursorMovementOptions',
'/EditorMenu/EditPointMenu',
'/EditorMenu/EditSelectRangeOptions',
'/EditorMenu/EditSelectRegionOptions',
'/EditorMenu/FadeMenu',
'/EditorMenu/LatchMenu',
'/EditorMenu/Link',
'/EditorMenu/LocateToMarker',
'/EditorMenu/LuaScripts',
'/EditorMenu/MIDI',
'/EditorMenu/MarkerMenu',
'/EditorMenu/MeterFalloff',
'/EditorMenu/MeterHold',
'/EditorMenu/MiscOptions',
'/EditorMenu/Monitoring',
'/EditorMenu/MoveActiveMarkMenu',
'/EditorMenu/MovePlayHeadMenu',
'/EditorMenu/PlayMenu',
'/EditorMenu/PrimaryClockMenu',
'/EditorMenu/Pullup',
'/EditorMenu/RegionEditOps',
'/EditorMenu/RegionGainMenu',
'/EditorMenu/RegionMenu',
'/EditorMenu/RegionMenuDuplicate',
'/EditorMenu/RegionMenuEdit',
'/EditorMenu/RegionMenuFades',
'/EditorMenu/RegionMenuGain',
'/EditorMenu/RegionMenuLayering',
'/EditorMenu/RegionMenuMIDI',
'/EditorMenu/RegionMenuPosition',
'/EditorMenu/RegionMenuRanges',
'/EditorMenu/RegionMenuTrim',
'/EditorMenu/RulerMenu',
'/EditorMenu/SavedViewMenu',
'/EditorMenu/ScrollMenu',
'/EditorMenu/SecondaryClockMenu',
'/EditorMenu/Select',
'/EditorMenu/SelectMenu',
'/EditorMenu/SeparateMenu',
'/EditorMenu/SetLoopMenu',
'/EditorMenu/SetPunchMenu',
'/EditorMenu/Solo',
'/EditorMenu/Subframes',
'/EditorMenu/SyncMenu',
'/EditorMenu/TempoMenu',
'/EditorMenu/Timecode',
'/EditorMenu/Tools',
'/EditorMenu/TrackHeightMenu',
'/EditorMenu/TrackMenu',
'/EditorMenu/VideoMonitorMenu',
'/EditorMenu/View',
'/EditorMenu/ZoomFocus',
'/EditorMenu/ZoomFocusMenu',
'/EditorMenu/ZoomMenu',
'/MouseMode/set-mouse-mode-audition',
'/MouseMode/set-mouse-mode-content',
'/MouseMode/set-mouse-mode-cut',
'/MouseMode/set-mouse-mode-draw',
'/MouseMode/set-mouse-mode-object',
'/MouseMode/set-mouse-mode-object-range',
'/MouseMode/set-mouse-mode-range',
'/MouseMode/set-mouse-mode-timefx',
'/Region/add-range-marker-from-region',
'/Region/add-range-markers-from-region',
'/Region/align-regions-end',
'/Region/align-regions-end-relative',
'/Region/align-regions-start',
'/Region/align-regions-start-relative',
'/Region/align-regions-sync',
'/Region/align-regions-sync-relative',
'/Region/alternate-nudge-backward',
'/Region/alternate-nudge-forward',
'/Region/alternate-set-fade-in-length',
'/Region/alternate-set-fade-out-length',
'/Region/boost-region-gain',
'/Region/bounce-regions-processed',
'/Region/bounce-regions-unprocessed',
'/Region/choose-top-region',
'/Region/choose-top-region-context-menu',
'/Region/close-region-gaps',
'/Region/combine-regions',
'/Region/cut-region-gain',
'/Region/duplicate-region',
'/Region/export-region',
'/Region/fork-region',
'/Region/insert-patch-change',
'/Region/insert-patch-change-context',
'/Region/insert-region-from-region-list',
'/Region/legatize-region',
'/Region/loop-region',
'/Region/loudness-analyze-region',
'/Region/lower-region',
'/Region/lower-region-to-bottom',
'/Region/multi-duplicate-region',
'/Region/naturalize-region',
'/Region/normalize-region',
'/Region/nudge-backward',
'/Region/nudge-backward-by-capture-offset',
'/Region/nudge-forward',
'/Region/nudge-forward-by-capture-offset',
'/Region/pitch-shift-region',
'/Region/place-transient',
'/Region/play-selected-regions',
'/Region/quantize-region',
'/Region/raise-region',
'/Region/raise-region-to-top',
'/Region/region-fill-track',
'/Region/remove-overlap',
'/Region/remove-region',
'/Region/remove-region-sync',
'/Region/rename-region',
'/Region/reset-region-gain',
'/Region/reset-region-gain-envelopes',
'/Region/reset-region-scale-amplitude',
'/Region/reverse-region',
'/Region/separate-under-region',
'/Region/sequence-regions',
'/Region/set-fade-in-length',
'/Region/set-fade-out-length',
'/Region/set-loop-from-region',
'/Region/set-punch-from-region',
'/Region/set-region-sync-position',
'/Region/set-selection-from-region',
'/Region/set-tempo-from-region',
'/Region/show-region-list-editor',
'/Region/show-region-properties',
'/Region/show-rhythm-ferret',
'/Region/snap-regions-to-grid',
'/Region/spectral-analyze-region',
'/Region/split-multichannel-region',
'/Region/split-region-at-transients',
'/Region/strip-region-silence',
'/Region/toggle-opaque-region',
'/Region/toggle-region-fade-in',
'/Region/toggle-region-fade-out',
'/Region/toggle-region-fades',
'/Region/toggle-region-gain-envelope-active',
'/Region/toggle-region-lock',
'/Region/toggle-region-lock-style',
'/Region/toggle-region-mute',
'/Region/toggle-region-video-lock',
'/Region/transform-region',
'/Region/transpose-region',
'/Region/trim-back',
'/Region/trim-front',
'/Region/trim-region-to-loop',
'/Region/trim-region-to-punch',
'/Region/trim-to-next-region',
'/Region/trim-to-previous-region',
'/Region/uncombine-regions',
'/RegionList/RegionListSort',
'/RegionList/SortAscending',
'/RegionList/SortByRegionEndinFile',
'/RegionList/SortByRegionLength',
'/RegionList/SortByRegionName',
'/RegionList/SortByRegionPosition',
'/RegionList/SortByRegionStartinFile',
'/RegionList/SortByRegionTimestamp',
'/RegionList/SortBySourceFileCreationDate',
'/RegionList/SortBySourceFileLength',
'/RegionList/SortBySourceFileName',
'/RegionList/SortBySourceFilesystem',
'/RegionList/SortDescending',
'/RegionList/removeUnusedRegions',
'/RegionList/rlAudition',
'/RegionList/rlHide',
'/RegionList/rlShow',
'/RegionList/rlShowAll',
'/RegionList/rlShowAuto',
'/Rulers/toggle-bbt-ruler',
'/Rulers/toggle-cd-marker-ruler',
'/Rulers/toggle-loop-punch-ruler',
'/Rulers/toggle-marker-ruler',
'/Rulers/toggle-meter-ruler',
'/Rulers/toggle-minsec-ruler',
'/Rulers/toggle-range-ruler',
'/Rulers/toggle-samples-ruler',
'/Rulers/toggle-tempo-ruler',
'/Rulers/toggle-timecode-ruler',
'/Rulers/toggle-video-ruler',
'/Snap/snap-to-asixteenthbeat',
'/Snap/snap-to-bar',
'/Snap/snap-to-beat',
'/Snap/snap-to-cd-frame',
'/Snap/snap-to-eighths',
'/Snap/snap-to-fifths',
'/Snap/snap-to-fourteenths',
'/Snap/snap-to-halves',
'/Snap/snap-to-mark',
'/Snap/snap-to-minutes',
'/Snap/snap-to-onetwentyeighths',
'/Snap/snap-to-quarters',
'/Snap/snap-to-region-boundary',
'/Snap/snap-to-region-end',
'/Snap/snap-to-region-start',
'/Snap/snap-to-region-sync',
'/Snap/snap-to-seconds',
'/Snap/snap-to-sevenths',
'/Snap/snap-to-sixths',
'/Snap/snap-to-sixtyfourths',
'/Snap/snap-to-tenths',
'/Snap/snap-to-thirds',
'/Snap/snap-to-thirtyseconds',
'/Snap/snap-to-timecode-frame',
'/Snap/snap-to-timecode-minutes',
'/Snap/snap-to-timecode-seconds',
'/Snap/snap-to-twelfths',
'/Snap/snap-to-twentieths',
'/Snap/snap-to-twentyeighths',
'/Snap/snap-to-twentyfourths',
'/Zoom/zoom-focus-center',
'/Zoom/zoom-focus-edit',
'/Zoom/zoom-focus-left',
'/Zoom/zoom-focus-mouse',
'/Zoom/zoom-focus-playhead',
'/Zoom/zoom-focus-right',
'/Mixer/ab-plugins',
'/Mixer/copy-processors',
'/Mixer/cut-processors',
'/Mixer/decrement-gain',
'/Mixer/delete-processors',
'/Mixer/increment-gain',
'/Mixer/mute',
'/Mixer/paste-processors',
'/Mixer/recenable',
'/Mixer/scroll-left',
'/Mixer/scroll-right',
'/Mixer/select-all-processors',
'/Mixer/select-none',
'/Mixer/show-editor',
'/Mixer/solo',
'/Mixer/toggle-midi-input-active',
'/Mixer/toggle-processors',
'/Mixer/unity-gain'
}

-- ============================================================================
function ardour_find_actions_in_component(self,pattern)
	matches={}
	for fname, f in pairs(self) do
		if string.find(fname, pattern) then
			table.insert(matches,fname)
		end
	end

	table.sort(matches)
	for i, fname in pairs(matches) do
		print(fname)
	end
	return matches
end

-- ============================================================================
local function ardour_create_action_functions(tokens)
	local i=1
	while tokens[i] do
		local str=""
		local split_tokens={}
		split_tokens=string.split(tokens[i],'/')

		if llength(split_tokens)>2 then

			local component=split_tokens[2]
			local action=split_tokens[3]

			if not(component or action) then goto _skip end

			if aa[component] == nil then 
				aa[component]={}
				local str="function aa." .. component .. ":dump() print_r(self) end "
				.. "function aa." .. component .. ":find(str) return ardour_find_actions_in_component(self,str) end "
				.. "function aa." .. component .. ":list() return self:find('.') end "
				load(str)()
			end
			--chars not allowd in method names - () [] ' ' can not start with number
			local action_=string.gsub(action, "%-", "_")

			local str="function aa." .. component .. ":" .. action_ .. "() CSO:access_action('" 
				.. component .. "/" .. action .. "' ) end"
			load(str)()
		end
		::_skip::
		i = i + 1
	end
end
-- ardour_create_action_functions()
ardour_create_action_functions(ardour_action_tokens)

--EOF
