#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            cso.cc
            interface.cc
    '''

    obj.export_includes = ['.']
    obj.defines      = [ 'PACKAGE="ardour_cso"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = ['.', './cso']
    obj.name         = 'libardour_cso'
    obj.target       = 'ardour_cso'
    obj.uselib       = 'LO'
    obj.use          = 'libardour libardour_cp libpbd'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')

def shutdown():
    autowaf.shutdown()
